Typography
HabitatMap/AirCasting pull request #532
Opened 2023-11-16 12:18 UTC by smialko

I added some typography styles based on Figma designs for future use.

2023-11-16 12:37 UTC, franiakat requested changes
⭐ Happy to be doing reviews again!

Please see the suggestions. :)

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +  font-family: "Roboto";
I think there is no other font used in the calendar feature, why don't we just set it once in `global-styles.ts`?

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +  color: #3e4449;
Please add this color to variables, also we can set the font color globally, as most often that would be true, can be then removed from all the elements.

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +  font-style: normal;
It's a default, don't have to specify that, please remove.

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +  line-height: 1.2;
Could be globally set as well I think?

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +`;
Here we can have just one component with a prop:
```suggestion
const H3 = styled.h3<{bold?: boolean}>`
  font-weight: ${(p) => p.bold ? '600' : '400'};
  font-size: 18px;
`;
```

I've written it here, but most probably should work.

2023-11-16 12:37 UTC, franiakat commented on app/javascript/react/assets/styles/Typography/Typography.style.tsx
> +`;
We can treat this uppercase feature as a prop as well, similar to bold.

2023-11-16 17:21 UTC, jankrzempek reviewed
It was a great opportunity to learn, thanks. Nothing more to add 😄

2023-11-21 08:53 UTC, franiakat approved these changes
Good to go! 🎖️ 
Please use the option of squash and merge.
![sqash](https://github.com/HabitatMap/AirCasting/assets/23078837/d3084a73-a5b8-4a94-94bd-5d5aa511a794)

2023-11-21 09:14 UTC, merged