Calendar header component
HabitatMap/AirCasting pull request #558
Opened 2024-01-10 10:38 UTC by jankrzempek

2024-01-11 13:41 UTC, smialko reviewed
review tip

2024-01-12 10:23 UTC, smialko requested changes
Awesome code! Noticed a few differences from the designs so I'm requesting changes, please check. Thanks!

2024-01-12 10:23 UTC, smialko commented on app/javascript/react/utils/media.ts
> +};
why? Could you add a comment or sth?  🙈

2024-01-15 09:31 UTC, jankrzempek commented on app/javascript/react/components/molecules/StationValueLabel/StationValueLabel.style.tsx
>      ${mint};
That's interesting, how can we know which one to implement, or both? How to approach it?

2024-01-15 09:33 UTC, jankrzempek commented on app/javascript/react/components/molecules/StationValueLabel/StationValueLabel.style.tsx
> +    border-radius: 0px;
One design says it should be, and the second says it should not. You right... asking Iwona now

2024-01-15 09:46 UTC, jankrzempek commented on app/javascript/react/components/molecules/CalendarStationHeader/CalendarStationHeader.style.tsx
> +    font-weight: 500;
<img width="593" alt="Zrzut ekranu 2024-01-15 o 10 45 53" src="https://github.com/HabitatMap/AirCasting/assets/44276070/4dc0b801-6028-44de-bf2d-1bedaf258bea">
Straight from designs

2024-01-15 09:47 UTC, jankrzempek commented on app/javascript/react/components/molecules/CalendarStationHeader/CalendarStationHeader.style.tsx
> +    text-transform: uppercase;
Thx, done!

2024-01-26 10:29 UTC, closed without merging