[WIP] Week view - Calendar
HabitatMap/AirCasting pull request #564
Opened 2024-01-24 19:08 UTC by jankrzempek

Please test the feature, as it will be ready. 
Do not consider the mobile view, it will be applied after ... let's call it an early review.
The popup with parameters is also missing, it will be applied in separate PR to make thing concise and readable'ish.

**Ticket:** https://trello.com/c/dAZx3K82/1744-week-view-calendar-component
**Goal:** Be able to see the data using bars and color them based on the given ranges. Be able to see the top, middle, and low parameters at the right'est bar.

2024-01-26 15:46 UTC, franiakat requested changes
I've added some explicite comments here, but there is also review branch `week-view-review`. Please take a look. There are some changes around naming I tried to follow the rule to reference element meaning, not its appearance. If an element is not a utility Element like HorizontalFlex could be, I'd rather stick to it. :)

2024-02-01 10:50 UTC, smialko reviewed
Great work! 🥳I have rather minor things, I was digging into your code yesterday and it's really easy to read and so 🐎-bas 👏

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/assets/styles/colors.ts
>  const grey400 = "#3E4449";
It's minor. 
We need to decide if we use `grey` or `gray`. Me and Kasia changed to `gray` in our PRs, but I checked and both are correct. `Gray` is American and `grey` is British. 
I'd go with `gray` bc AirCasting is american project but let's decide together @franiakat 🥸

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/assets/styles/colors.ts
> -const green = "#86d175";
I'm wondering - is there a specific reason why you changed that? 
I don't mind but I believe such changes can cause rebase/merge conflicts in the future, little but annoying to solve 😅

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/components/DayView/DayView.style.tsx
> +};
can you move it to utils? I think this can be reused, maybe in my months view 🤔

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/components/DayView/DayView.style.tsx
> +  const definedPercentage = (value / max) * 100;
did you consider the case when value is a negative number? I know we have temp so it's possible, isn't it? 🤔

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/components/WeekView/WeeklyMockData.tsx
> +];
I know it's mocked but to be sure that you know. It should be the other way around. It's `today` and 6 previous days. Unless it works different on week view but I'm 99% sure it's not.

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/pages/CalendarPage.tsx
>  `;
is it just for testing or foreva? 🫠 If it stays can you make `CalendarPage.style.tsx` for that?

2024-02-01 10:50 UTC, smialko commented on app/javascript/react/utils/ThresholdsValues.ts
> +}
👏 thanks! I'll use them :D

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/components/DayView/DayView.style.tsx
> +  bottom: -20px;
I'd just group position, left and bottom properties, as they all define the position together.

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/components/DayView/DayView.tsx
> +      >
Please use transient props, as mentioned in Monika's PR, those props here are passed to React, to DOM elements and are not a native properties of div element, console complaining ;)

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/components/WeekView/WeeklyMockData.tsx
> +};
This isn't needed, as we can use the values selected from the story at this point - it's done in Calendar Page rn. :)

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/components/WeekView/WeekView.tsx
> +};
You could also have it this way:
```suggestion
const { min, low, middle, high, max } = thresholds; 

  return (
    <S.Container>
      <S.WeekContainer>
        {weeklyData
          .sort((a, b) => (a.date > b.date ? 1 : -1))
          .map(({ value, date }, index) => (
            <DayView
              key={index}
              value={value}
              date={date}
              thresholdsValues={thresholdsValues}
            />
          ))}
      </S.WeekContainer>
      <S.DesktopLabel>
        <ThresholdsIndicator
          values={[min, middle, max]}
        />
      </S.DesktopLabel>
      <S.MobileLabel>
        <ThresholdsIndicator values={[min, low,  middle, high, max]} />
      </S.MobileLabel>
    </S.Container>
  );
};
```

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/utils/ThresholdColors.ts
> +import { thresholdsValues } from "../components/WeekView/WeeklyMockData";
The file name should start with lowercase: `thresholdColors.ts`

2024-02-02 09:31 UTC, franiakat commented on app/javascript/react/utils/ThresholdsValues.ts
> +export interface ThresholdsValues {
I think that now we have this interface in types folder, could you remove this one if that's correct?

2024-02-02 10:40 UTC, franiakat commented on app/javascript/react/components/WeekView/WeekView.tsx
> +        />
`key` property is missing.

2024-02-02 15:34 UTC, franiakat approved these changes
Looks good to me! I think you cannot follow the QA Flow from here, are you able to do the deploys? https://www.notion.so/QA-New-Flow-ec6f92087e08403ea061ccc5df8dcea4
If you can't I'll do it on Monday.

We wouldn't go to production anyway today. ;)

2024-02-02 16:32 UTC, merged