Fix threshold configurator
HabitatMap/AirCasting pull request #630
Opened 2024-05-08 12:42 UTC by evulins

Fix styling and behaviour in Threshold configurator 
[Trello card with details ](https://trello.com/c/ZK3ltmBp/1859-calendar-page-thresholds-configurator-mobiledesktop)

2024-05-09 12:09 UTC, smialko approved these changes
Good job, just one minor comment from me :)

2024-05-09 12:09 UTC, smialko commented on app/javascript/react/components/ThresholdConfigurator/ThresholdConfigurator.style.tsx
> +    background: #fff;
can you use` colors.white` for consistency?

2024-05-09 15:32 UTC, jankrzempek requested changes
On the mobile - iPhone simulator it behaves weirdly. Sometimes it jump or flashes, and sometimes all the line turns red with no reason. Please see the following movie and screenshot.
![Simulator Screenshot - iPhone 15 Pro - 2024-05-09 at 17 27 04](https://github.com/HabitatMap/AirCasting/assets/44276070/9175f4e4-574a-4bd6-9a8e-2b89af7a73bb)

https://github.com/HabitatMap/AirCasting/assets/44276070/1b42f912-8716-41ae-a354-45505c20ac8d

2024-05-10 07:06 UTC, smialko approved these changes
Works well, looks great - very good work! :)

2024-05-14 09:55 UTC, merged